spring:
  application:
    name: myapp
  config:
    import: 'optional:configserver:http://localhost:8060'
  profiles:
    active: dev # dev - prod
  cloud:
    config:
      label: master # master - 1.0.0
      username: admin
      password: admin
encrypt:
  key: 1234567890ChangeMe
# expose the /refresh endpoint used for the @RefreshScope bean
# /actuator/refresh re-load the boot strap context and refresh the @RefreshScope beans.
management:
  endpoints:
    web:
      exposure:
        include: refresh